[17.0] [MIG] tg_website_sale_affiliate
it-projects-llc/tg-addons pull request #8
Opened 2024-09-23 10:17 UTC by azimkhankuat

[17.0] [MIG] tg_website_sale_affiliate

2024-09-24 05:29 UTC, em230418 requested changes

2024-09-24 05:29 UTC, em230418 commented on tg_website_sale_affiliate/models/sale_affiliate.py
> +            """,
Если тут добавили пробелы из-за линтера, то предлагаю пробелы убрать и добавить исключение для такого правила.

2024-09-24 05:29 UTC, em230418 commented on tg_website_sale_affiliate/models/sale_affiliate.py
> +            """,
Если тут добавили пробелы из-за линтера, то предлагаю пробелы убрать и добавить исключение для такого правила.

2024-09-24 05:29 UTC, em230418 commented on tg_website_sale_affiliate/wizard/sale_coupon_apply_code.py
> +        return action
Если реализация оригинального метода action_apply позволяет без особых проблем наследоваться и добавить свой код, то предлагаю так и делать, а не копировать реализацию оригинального метода и вставлять свой код.

Если реализация оригинального метода action_apply не позволяет, то просьба пояснить что именно мешает это сделать.

2024-09-24 05:29 UTC, em230418 commented on tg_website_sale_affiliate/wizard/sale_coupon_apply_code.py
>                      },
В случае, если можно нормально наследоваться от action_apply, то предлагаю
1. в начале метода добавить переменные coupon_code = self.coupon_code, order = self.order_id.
2. не заводить переменную reward, если линтер позволяет.

Таким образом diff будет меньше нагромождать.

2024-09-24 05:29 UTC, em230418 commented on tg_website_sale_affiliate/__manifest__.py
> +        # "views/coupon_program_views.xml",
В 14.0 вьюха из комментируемого файла не позволяет менять поле promo_code_usage если в контексте задан lock_promo_code_usage и он имеет положительное значение.

В 17.0 надо это поведение оставить. Если этого поля или другого поля, которая ее по сути меняет, не существует, то тогда надо вообще убрать этот файл и ее упоминание в манифесте.

2024-09-25 11:52 UTC, em230418 requested changes
Частичный обзор

2024-09-25 11:52 UTC, em230418 commented on tg_website_sale_affiliate/views/portal_templates.xml
> +                        </td>
1. В копии боевой базы на 14.0 кнопочки выравниваются по правому краю.
![Снимок экрана_2024-09-25_16-09-39](https://github.com/user-attachments/assets/0857f31f-b941-41a0-b077-9350471de407)
В текущей реализации так не выравниваются, а надо также по правому краю.
![2024-09-25_16-15](https://github.com/user-attachments/assets/d501d13a-adb6-4b74-b1ea-b75a25cd220b)

2024-09-25 11:52 UTC, em230418 commented on tg_website_sale_affiliate/views/portal_templates.xml
> +                            <a
2. Возле домика надо вставить хлебную крошку.
![2024-09-25_16-15](https://github.com/user-attachments/assets/d501d13a-adb6-4b74-b1ea-b75a25cd220b)
Как тут по ссылке `/my/orders`
![Снимок экрана_2024-09-25_16-20-31](https://github.com/user-attachments/assets/594d2bcc-a601-430f-ae50-db0e4ba3f23e)

2024-09-25 11:52 UTC, em230418 commented on tg_website_sale_affiliate/views/portal_templates.xml
> +        </xpath>
В `/my` раздел Affiliates выглядит уныло по сравнению с остальными.
![2024-09-25_16-23](https://github.com/user-attachments/assets/8b866ac5-5707-4970-948d-f9a5c45bfb46)

Как готовую иконку предлагаю использовать `/portal/static/src/img/portal-connection.svg` и серый текст "View your affiliations"

2024-09-25 11:52 UTC, em230418 commented on tg_website_sale_affiliate/views/res_partner_views.xml
> +            </div>
Надпись Affiliates и количество сильно прилипло к иконке. Сравнения есть другие
![Снимок экрана_2024-09-25_16-34-50](https://github.com/user-attachments/assets/26bbc4b5-bb42-4c23-a99a-eb2bf7957ecd)

2024-09-25 11:52 UTC, em230418 commented on tg_website_sale_affiliate/models/sale_order.py
> +        return res + super()._get_applicable_no_code_promo_program()
Метода `_get_applicable_no_code_promo_program` не существует в 14.0

2024-09-26 11:11 UTC, em230418 commented on tg_website_sale_affiliate/views/res_partner_views.xml
>                      icon="fa-handshake-o"
достаточно добавить fa-pull-left в свойство icon.

2024-09-26 11:11 UTC, em230418 commented on tg_website_sale_affiliate/static/src/css/style.css
> +}
После добавления fa-pull-left это надо убрать.

2024-09-26 11:11 UTC, em230418 commented on tg_website_sale_affiliate/__manifest__.py
> +    },
После добавления fa-pull-left это надо убрать.

2024-09-26 11:11 UTC, em230418 commented on tg_website_sale_affiliate/models/sale_order.py
> -        return res + super()._get_applicable_no_code_promo_program()
В 14.0 если к закаку привязан affiliate, то автоматически применяется купон с кодом (affiliate_id.code_promo_program_id).
В 17.0 надо вернуть эту функциональность

2024-09-26 11:11 UTC, em230418 commented on tg_website_sale_affiliate/views/portal_templates.xml
> +                            </div>
Для решения задачи, которую я описал [тут](https://github.com/it-projects-llc/tg-addons/pull/8/files/f53b3d0607dfcacf2a5a33199f1c7f47555f4f03#r1775043963), достаточно было text-right на text-end.

Также предлагаю тут вернуть как было с правкой text-right/text-end, чтобы в итогов коммите, где будет зафиксирована миграция, не было лишних изменений. Под вернуть как было подразумеваю не разделять `<td><t t-esc="affiliate.name" /></td>` на 3 строки.

2024-09-26 11:51 UTC, azimkhankuat commented on tg_website_sale_affiliate/models/sale_order.py
> -        return res + super()._get_applicable_no_code_promo_program()
> В 14.0 если к закаку привязан affiliate, то автоматически применяется купон с кодом (affiliate_id.code_promo_program_id). В 17.0 надо вернуть эту функциональность

Как можно посмотреть какой метод является заменой в 17.0?

2024-10-02 06:18 UTC, closed without merging